spring:
  #数据库配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: aA010608

  #文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t7YQxAheN9fX98kTLjb
    accessKeySecret: 24gxhS1VCsJgbH9D6wdmMoVOqK9Qtj
    bucketName: web-tilasw
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug